repos:
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.9.0      # Insert the latest tag here
    hooks:
    -   id: pre-commit-update
#      args: [--dry-run]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
-   repo: https://github.com/psf/black
    rev: '26.1.0'
    hooks:
    -   id: black
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
#-   repo: local
#    hooks:
#    -   id: mypy
#        name: poetry_mypy
#        entry: poetry run mypy --config-file pyproject.toml .
#        language: system
#        pass_filenames: false
